import json
from typing import Any, List, Optional, Tuple

from sqlalchemy import text
from sqlmodel import Session

from config import settings
from database import engine
from services.ollama_client import OllamaClient, OllamaClientError


class EmbeddingStore:
    """Store and query article embeddings using sqlite-vec.

    Embeddings are generated by Gemini or a local Ollama embedding model and
    stored in a virtual table so RAG can retrieve semantically similar articles
    without another AI call at query time.
    """

    TABLE_NAME = "article_embeddings"

    def __init__(
        self,
        model: Optional[str] = None,
        enabled: Optional[bool] = None,
    ):
        # When Gemini is the primary provider, use Gemini embeddings by default.
        self.use_gemini = settings.AI_PROVIDER == "gemini"
        if self.use_gemini:
            self.model = model or settings.GEMINI_EMBEDDING_MODEL
            self.enabled = enabled if enabled is not None else True
        else:
            self.model = model or settings.OLLAMA_EMBEDDING_MODEL
            self.enabled = enabled if enabled is not None else settings.OLLAMA_EMBEDDING_ENABLED
        self._ollama_client: Optional[OllamaClient] = None
        self._gemini_client: Optional[Any] = None

    def _get_ollama_client(self) -> OllamaClient:
        if self._ollama_client is None:
            self._ollama_client = OllamaClient()
        return self._ollama_client

    def _get_gemini_client(self) -> Any:
        if self._gemini_client is None:
            from services.gemini_client import GeminiClient

            self._gemini_client = GeminiClient()
        return self._gemini_client

    def _serialize(self, vector: List[float]) -> str:
        """Serialize a vector to a JSON array string for sqlite-vec."""
        return json.dumps(vector, separators=(",", ":"))

    def _deserialize(self, value) -> List[float]:
        if isinstance(value, str):
            return json.loads(value)
        if isinstance(value, bytes):
            return json.loads(value.decode("utf-8"))
        return list(value)

    def create_embedding(self, article_id: int, text: str) -> Optional[List[float]]:
        """Generate and store an embedding for a single article."""
        if not self.enabled:
            return None
        if not text or not text.strip():
            return None

        text = text.strip()[:1000]
        try:
            if self.use_gemini:
                vector = self._get_gemini_client().embed(
                    text=text,
                    task_name=f"article_embedding:{article_id}",
                )
            else:
                vector = self._get_ollama_client().embed(
                    text=text,
                    model=self.model,
                    task_name=f"article_embedding:{article_id}",
                )
        except Exception as e:
            print(f"[embedding_store] failed to embed article {article_id}: {e}")
            # Try Ollama as fallback if Gemini failed.
            if self.use_gemini:
                try:
                    vector = self._get_ollama_client().embed(
                        text=text,
                        model=settings.OLLAMA_EMBEDDING_MODEL,
                        task_name=f"article_embedding:{article_id}:fallback",
                    )
                except Exception as e2:
                    print(f"[embedding_store] ollama fallback failed: {e2}")
                    return None
            else:
                return None

        self.save(article_id, vector)
        return vector

    def save(self, article_id: int, vector: List[float]) -> None:
        """Insert or replace an embedding vector."""
        with engine.connect() as conn:
            conn.execute(
                text(
                    f"""
                    INSERT OR REPLACE INTO {self.TABLE_NAME} (article_id, embedding)
                    VALUES (:article_id, :embedding)
                    """
                ),
                {
                    "article_id": article_id,
                    "embedding": self._serialize(vector),
                },
            )
            conn.commit()

    def find_similar(
        self,
        vector: List[float],
        k: int = 5,
    ) -> List[Tuple[int, float]]:
        """Return the top-k most similar article ids and their distances."""
        if not vector:
            return []
        with engine.connect() as conn:
            rows = conn.execute(
                text(
                    f"""
                    SELECT article_id, distance
                    FROM {self.TABLE_NAME}
                    WHERE embedding MATCH :embedding
                    AND k = :k
                    """
                ),
                {
                    "embedding": self._serialize(vector),
                    "k": k,
                },
            ).fetchall()
        return [(int(row[0]), float(row[1])) for row in rows]

    def find_similar_for_text(self, text: str, k: int = 5) -> List[Tuple[int, float]]:
        """Embed the text and return similar articles."""
        if not self.enabled or not text:
            return []
        text = text.strip()[:1000]
        try:
            if self.use_gemini:
                vector = self._get_gemini_client().embed(
                    text=text,
                    task_name="article_embedding:query",
                )
            else:
                vector = self._get_ollama_client().embed(
                    text=text,
                    model=self.model,
                    task_name="article_embedding:query",
                )
        except Exception as e:
            print(f"[embedding_store] failed to embed query: {e}")
            # Try Ollama fallback if Gemini failed.
            if self.use_gemini:
                try:
                    vector = self._get_ollama_client().embed(
                        text=text,
                        model=settings.OLLAMA_EMBEDDING_MODEL,
                        task_name="article_embedding:query:fallback",
                    )
                except Exception as e2:
                    print(f"[embedding_store] ollama query fallback failed: {e2}")
                    return []
            else:
                return []
        return self.find_similar(vector, k=k)

    def get_existing_article_ids(self, article_ids: List[int]) -> List[int]:
        """Return which of the provided article ids already have embeddings."""
        if not article_ids:
            return []
        with engine.connect() as conn:
            rows = conn.execute(
                text(
                    f"""
                    SELECT article_id FROM {self.TABLE_NAME}
                    WHERE article_id IN :article_ids
                    """
                ),
                {"article_ids": tuple(article_ids)},
            ).fetchall()
        return [int(row[0]) for row in rows]

    def delete_for_article(self, article_id: int) -> None:
        """Remove an embedding."""
        with engine.connect() as conn:
            conn.execute(
                text(f"DELETE FROM {self.TABLE_NAME} WHERE article_id = :article_id"),
                {"article_id": article_id},
            )
            conn.commit()
