import json
from typing import List, Optional, Tuple

from sqlalchemy import text
from sqlmodel import Session

from config import settings
from database import engine
from services.ollama_client import OllamaClient, OllamaClientError


class EmbeddingStore:
    """Store and query article embeddings using sqlite-vec.

    Embeddings are generated by a local Ollama embedding model and stored in a
    virtual table so RAG can retrieve semantically similar articles without
    another AI call at query time.
    """

    TABLE_NAME = "article_embeddings"

    def __init__(
        self,
        model: str = settings.OLLAMA_EMBEDDING_MODEL,
        enabled: bool = settings.OLLAMA_EMBEDDING_ENABLED,
    ):
        self.model = model
        self.enabled = enabled
        self._client = OllamaClient()

    def _serialize(self, vector: List[float]) -> str:
        """Serialize a vector to a JSON array string for sqlite-vec."""
        return json.dumps(vector, separators=(",", ":"))

    def _deserialize(self, value) -> List[float]:
        if isinstance(value, str):
            return json.loads(value)
        if isinstance(value, bytes):
            return json.loads(value.decode("utf-8"))
        return list(value)

    def create_embedding(self, article_id: int, text: str) -> Optional[List[float]]:
        """Generate and store an embedding for a single article."""
        if not self.enabled:
            return None
        if not text or not text.strip():
            return None
        try:
            vector = self._client.embed(
                text=text.strip()[:1000],
                model=self.model,
                task_name=f"article_embedding:{article_id}",
            )
        except OllamaClientError as e:
            print(f"[embedding_store] failed to embed article {article_id}: {e}")
            return None

        self.save(article_id, vector)
        return vector

    def save(self, article_id: int, vector: List[float]) -> None:
        """Insert or replace an embedding vector."""
        with engine.connect() as conn:
            conn.execute(
                text(
                    f"""
                    INSERT OR REPLACE INTO {self.TABLE_NAME} (article_id, embedding)
                    VALUES (:article_id, :embedding)
                    """
                ),
                {
                    "article_id": article_id,
                    "embedding": self._serialize(vector),
                },
            )
            conn.commit()

    def find_similar(
        self,
        vector: List[float],
        k: int = 5,
    ) -> List[Tuple[int, float]]:
        """Return the top-k most similar article ids and their distances."""
        if not vector:
            return []
        with engine.connect() as conn:
            rows = conn.execute(
                text(
                    f"""
                    SELECT article_id, distance
                    FROM {self.TABLE_NAME}
                    WHERE embedding MATCH :embedding
                    AND k = :k
                    """
                ),
                {
                    "embedding": self._serialize(vector),
                    "k": k,
                },
            ).fetchall()
        return [(int(row[0]), float(row[1])) for row in rows]

    def find_similar_for_text(self, text: str, k: int = 5) -> List[Tuple[int, float]]:
        """Embed the text and return similar articles."""
        if not self.enabled or not text:
            return []
        try:
            vector = self._client.embed(
                text=text.strip()[:1000],
                model=self.model,
                task_name="article_embedding:query",
            )
        except OllamaClientError as e:
            print(f"[embedding_store] failed to embed query: {e}")
            return []
        return self.find_similar(vector, k=k)

    def get_existing_article_ids(self, article_ids: List[int]) -> List[int]:
        """Return which of the provided article ids already have embeddings."""
        if not article_ids:
            return []
        with engine.connect() as conn:
            rows = conn.execute(
                text(
                    f"""
                    SELECT article_id FROM {self.TABLE_NAME}
                    WHERE article_id IN :article_ids
                    """
                ),
                {"article_ids": tuple(article_ids)},
            ).fetchall()
        return [int(row[0]) for row in rows]

    def delete_for_article(self, article_id: int) -> None:
        """Remove an embedding."""
        with engine.connect() as conn:
            conn.execute(
                text(f"DELETE FROM {self.TABLE_NAME} WHERE article_id = :article_id"),
                {"article_id": article_id},
            )
            conn.commit()
