import json
import logging
from typing import Any, Dict, List, Optional, Tuple

from sqlalchemy import text
from sqlmodel import Session

from config import settings
from database import engine
from services.ollama_client import OllamaClient

logger = logging.getLogger(__name__)

# BGE-M3 embedding model served via Ollama. Used for hybrid news search.
# BGE-M3 produces 1024-dimensional dense vectors and supports multilingual
# text (including Vietnamese), making it well-suited for this app.
BGE_M3_MODEL = "bge-m3"
BGE_M3_DIMENSION = 1024


class EmbeddingStore:
    """Store and query article embeddings using sqlite-vec.

    Embeddings are generated by Gemini or a local Ollama embedding model and
    stored in a virtual table so RAG can retrieve semantically similar articles
    without another AI call at query time.
    """

    TABLE_NAME = "article_embeddings"

    def __init__(
        self,
        model: Optional[str] = None,
        enabled: Optional[bool] = None,
    ):
        # When Gemini is the primary provider, use Gemini embeddings by default.
        self.use_gemini = settings.AI_PROVIDER == "gemini"
        if self.use_gemini:
            self.model = model or settings.GEMINI_EMBEDDING_MODEL
            self.enabled = enabled if enabled is not None else True
        else:
            self.model = model or settings.OLLAMA_EMBEDDING_MODEL
            self.enabled = enabled if enabled is not None else settings.OLLAMA_EMBEDDING_ENABLED
        self._ollama_client: Optional[OllamaClient] = None
        self._gemini_client: Optional[Any] = None
        self._dimension = (
            settings.GEMINI_EMBEDDING_DIMENSION
            if self.use_gemini
            else settings.OLLAMA_EMBEDDING_DIMENSION
        )

    def _get_ollama_client(self) -> OllamaClient:
        if self._ollama_client is None:
            self._ollama_client = OllamaClient()
        return self._ollama_client

    def _get_gemini_client(self) -> Any:
        if self._gemini_client is None:
            from services.gemini_client import GeminiClient

            self._gemini_client = GeminiClient()
        return self._gemini_client

    def _serialize(self, vector: List[float]) -> str:
        """Serialize a vector to a JSON array string for sqlite-vec."""
        return json.dumps(vector, separators=(",", ":"))

    def _deserialize(self, value) -> List[float]:
        if isinstance(value, str):
            return json.loads(value)
        if isinstance(value, bytes):
            return json.loads(value.decode("utf-8"))
        return list(value)

    def create_embedding(self, article_id: int, text: str) -> Optional[List[float]]:
        """Generate and store an embedding for a single article."""
        results = self.create_embeddings_batch([(article_id, text)])
        return results.get(article_id)

    def create_embeddings_batch(
        self, items: List[Tuple[int, str]]
    ) -> Dict[int, Optional[List[float]]]:
        """Generate and store embeddings for multiple articles in one API call.

        Returns a mapping of article_id to embedding vector (or None on failure).
        """
        result: Dict[int, Optional[List[float]]] = {}
        if not self.enabled or not items:
            return result

        valid_items = [
            (aid, text.strip()[:1000]) for aid, text in items if text and text.strip()
        ]
        if not valid_items:
            return result

        texts = [text for _, text in valid_items]
        ids = [aid for aid, _ in valid_items]
        vectors: List[Optional[List[float]]] = []

        try:
            if self.use_gemini:
                batch_vectors = self._get_gemini_client().embed_batch(
                    texts,
                    task_name="article_embedding_batch",
                )
                vectors.extend(batch_vectors)
            else:
                for text in texts:
                    vector = self._get_ollama_client().embed(
                        text=text,
                        model=self.model,
                        task_name="article_embedding_batch",
                    )
                    vectors.append(vector)
        except Exception as e:
            print(f"[embedding_store] batch embed failed: {e}")
            # Fall back to single-item calls.
            for text in texts:
                try:
                    if self.use_gemini:
                        vectors.append(
                            self._get_gemini_client().embed(
                                text=text,
                                task_name="article_embedding_single",
                            )
                        )
                    else:
                        vectors.append(
                            self._get_ollama_client().embed(
                                text=text,
                                model=self.model,
                                task_name="article_embedding_single",
                            )
                        )
                except Exception as e2:
                    print(f"[embedding_store] single embed failed: {e2}")
                    vectors.append(None)

        # Skip vectors whose dimension doesn't match the table to avoid sqlite-vec
        # "Error opening vector blob" errors.
        expected = self._dimension
        validated_vectors: List[Optional[List[float]]] = []
        for vector in vectors:
            if vector is not None and len(vector) != expected:
                print(
                    f"[embedding_store] vector dimension mismatch: expected {expected}, got {len(vector)}"
                )
                validated_vectors.append(None)
            else:
                validated_vectors.append(vector)
        vectors = validated_vectors

        # Save all successful embeddings in a single transaction.
        to_save = [
            (aid, vector) for aid, vector in zip(ids, vectors) if vector is not None
        ]
        try:
            self.save_batch(to_save)
        except Exception as e:
            print(f"[embedding_store] failed to save embedding batch: {e}")
            for aid, _ in to_save:
                result[aid] = None
            return result

        for aid, vector in zip(ids, vectors):
            result[aid] = vector
        return result

    def save(self, article_id: int, vector: List[float]) -> None:
        """Insert or replace an embedding vector."""
        self.save_batch([(article_id, vector)])

    def save_batch(
        self, items: List[Tuple[int, List[float]]]
    ) -> None:
        """Insert or replace multiple embedding vectors in one transaction."""
        if not items:
            return
        expected = self._dimension
        valid_items = [
            (article_id, vector)
            for article_id, vector in items
            if len(vector) == expected
        ]
        if not valid_items:
            print(f"[embedding_store] no valid vectors to save (expected {expected} dims)")
            return
        with engine.begin() as conn:
            for article_id, vector in valid_items:
                conn.execute(
                    text(
                        f"""
                        INSERT OR REPLACE INTO {self.TABLE_NAME} (article_id, embedding)
                        VALUES (:article_id, vec_f32(:embedding))
                        """
                    ),
                    {
                        "article_id": article_id,
                        "embedding": self._serialize(vector),
                    },
                )

    def find_similar(
        self,
        vector: List[float],
        k: int = 5,
    ) -> List[Tuple[int, float]]:
        """Return the top-k most similar article ids and their distances."""
        if not vector:
            return []
        with engine.connect() as conn:
            rows = conn.execute(
                text(
                    f"""
                    SELECT article_id, vec_distance_L2(embedding, vec_f32(:embedding)) AS distance
                    FROM {self.TABLE_NAME}
                    ORDER BY distance
                    LIMIT :k
                    """
                ),
                {
                    "embedding": self._serialize(vector),
                    "k": k,
                },
            ).fetchall()
        return [(int(row[0]), float(row[1])) for row in rows]

    def find_similar_for_text(self, text: str, k: int = 5) -> List[Tuple[int, float]]:
        """Embed the text and return similar articles."""
        if not self.enabled or not text:
            return []
        text = text.strip()[:1000]
        try:
            if self.use_gemini:
                vector = self._get_gemini_client().embed(
                    text=text,
                    task_name="article_embedding:query",
                )
            else:
                vector = self._get_ollama_client().embed(
                    text=text,
                    model=self.model,
                    task_name="article_embedding:query",
                )
        except Exception as e:
            print(f"[embedding_store] failed to embed query: {e}")
            # Try Ollama fallback if Gemini failed.
            if self.use_gemini:
                try:
                    vector = self._get_ollama_client().embed(
                        text=text,
                        model=settings.OLLAMA_EMBEDDING_MODEL,
                        task_name="article_embedding:query:fallback",
                    )
                except Exception as e2:
                    print(f"[embedding_store] ollama query fallback failed: {e2}")
                    return []
            else:
                return []
        return self.find_similar(vector, k=k)

    def get_existing_article_ids(self, article_ids: List[int]) -> List[int]:
        """Return which of the provided article ids already have embeddings."""
        if not article_ids:
            return []
        with engine.connect() as conn:
            rows = conn.execute(
                text(
                    f"""
                    SELECT article_id FROM {self.TABLE_NAME}
                    WHERE article_id IN :article_ids
                    """
                ),
                {"article_ids": tuple(article_ids)},
            ).fetchall()
        return [int(row[0]) for row in rows]

    def delete_for_article(self, article_id: int) -> None:
        """Remove an embedding."""
        with engine.begin() as conn:
            conn.execute(
                text(f"DELETE FROM {self.TABLE_NAME} WHERE article_id = :article_id"),
                {"article_id": article_id},
            )


# ---------------------------------------------------------------------------
# Module-level BGE-M3 embedding helpers (for hybrid news search)
# ---------------------------------------------------------------------------

def _ollama_bge_m3_available() -> bool:
    """Return True if Ollama is enabled and the bge-m3 model can be reached."""
    if not settings.OLLAMA_ENABLED:
        return False
    try:
        client = OllamaClient()
        # Quick probe: a tiny embed call. If Ollama is down or the model is
        # missing, this raises OllamaClientError.
        client.embed(text="ping", model=BGE_M3_MODEL, task_name="bge_m3_probe")
        return True
    except Exception as e:
        logger.debug("BGE-M3 via Ollama unavailable: %s", e)
        return False


# Cache the availability check so we don't probe on every call.
_bge_m3_available_cache: Optional[bool] = None


def _is_bge_m3_available() -> bool:
    global _bge_m3_available_cache
    if _bge_m3_available_cache is None:
        _bge_m3_available_cache = _ollama_bge_m3_available()
        if _bge_m3_available_cache:
            logger.info("BGE-M3 embedding via Ollama is available")
        else:
            logger.info("BGE-M3 not available, will fall back to existing embedding method")
    return _bge_m3_available_cache


def _embed_via_bge_m3(text: str) -> Optional[List[float]]:
    """Generate a single embedding using Ollama BGE-M3. Returns None on failure."""
    try:
        client = OllamaClient()
        vector = client.embed(
            text=text,
            model=BGE_M3_MODEL,
            task_name="bge_m3_embed",
        )
        if isinstance(vector, list) and len(vector) == BGE_M3_DIMENSION:
            return vector
        logger.warning(
            "BGE-M3 returned unexpected dimension: expected %d, got %s",
            BGE_M3_DIMENSION,
            len(vector) if isinstance(vector, list) else type(vector),
        )
        return None
    except Exception as e:
        logger.warning("BGE-M3 single embed failed: %s", e)
        return None


def _embed_batch_via_bge_m3(texts: List[str]) -> Optional[List[List[float]]]:
    """Generate embeddings for multiple texts using Ollama BGE-M3.

    Ollama's /api/embeddings endpoint only accepts a single prompt, so we
    loop over the texts. Returns None if any call fails (caller falls back).
    """
    try:
        client = OllamaClient()
        vectors: List[List[float]] = []
        for text in texts:
            vector = client.embed(
                text=text,
                model=BGE_M3_MODEL,
                task_name="bge_m3_embed_batch",
            )
            if not isinstance(vector, list) or len(vector) != BGE_M3_DIMENSION:
                logger.warning(
                    "BGE-M3 batch returned unexpected dimension: expected %d, got %s",
                    BGE_M3_DIMENSION,
                    len(vector) if isinstance(vector, list) else type(vector),
                )
                return None
            vectors.append(vector)
        return vectors
    except Exception as e:
        logger.warning("BGE-M3 batch embed failed: %s", e)
        return None


def _embed_via_existing(text: str) -> Optional[List[float]]:
    """Generate a single embedding using the existing EmbeddingStore method."""
    try:
        store = EmbeddingStore()
        use_gemini = store.use_gemini
        if use_gemini:
            return store._get_gemini_client().embed(
                text=text,
                task_name="get_embedding:fallback",
            )
        else:
            return store._get_ollama_client().embed(
                text=text,
                model=settings.OLLAMA_EMBEDDING_MODEL,
                task_name="get_embedding:fallback",
            )
    except Exception as e:
        logger.warning("Existing embedding method failed: %s", e)
        return None


def _embed_batch_via_existing(texts: List[str]) -> Optional[List[List[float]]]:
    """Generate batch embeddings using the existing EmbeddingStore method."""
    try:
        store = EmbeddingStore()
        use_gemini = store.use_gemini
        if use_gemini:
            return store._get_gemini_client().embed_batch(
                texts,
                task_name="get_embeddings:fallback",
            )
        else:
            vectors: List[List[float]] = []
            for text in texts:
                vectors.append(
                    store._get_ollama_client().embed(
                        text=text,
                        model=settings.OLLAMA_EMBEDDING_MODEL,
                        task_name="get_embeddings:fallback",
                    )
                )
            return vectors
    except Exception as e:
        logger.warning("Existing batch embedding method failed: %s", e)
        return None


def get_embedding(text: str) -> List[float]:
    """Generate an embedding vector for a single text.

    Tries Ollama BGE-M3 first (multilingual, 1024-dim). Falls back to the
    existing embedding method (Gemini or nomic-embed-text) if BGE-M3 is
    unavailable. Returns an empty list if all methods fail.
    """
    if not text or not text.strip():
        return []
    text = text.strip()[:1000]

    if _is_bge_m3_available():
        vector = _embed_via_bge_m3(text)
        if vector is not None:
            return vector
        # BGE-M3 failed for this call; invalidate cache and try fallback.
        global _bge_m3_available_cache
        _bge_m3_available_cache = None

    vector = _embed_via_existing(text)
    if vector is not None:
        return vector
    return []


def get_embeddings(texts: List[str]) -> List[List[float]]:
    """Generate embedding vectors for multiple texts.

    Tries Ollama BGE-M3 first, then falls back to the existing method.
    Returns a list aligned with the input (empty list for failed items).
    """
    if not texts:
        return []
    cleaned = [t.strip()[:1000] if t else "" for t in texts]

    if _is_bge_m3_available():
        vectors = _embed_batch_via_bge_m3(cleaned)
        if vectors is not None:
            return vectors
        global _bge_m3_available_cache
        _bge_m3_available_cache = None

    vectors = _embed_batch_via_existing(cleaned)
    if vectors is not None:
        return vectors
    return [[] for _ in cleaned]
